pull_request_rules:
  - name: rebase and merge when passing all checks
    conditions:
      - base=master
      - status-success=Travis CI - Pull Request
      - label="merge-when-passing"
      - label!="work-in-progress"
      - "approved-reviews-by=@flux-framework/core"
      - "#approved-reviews-by>0"
      - "#changes-requested-reviews-by=0"
      - -title~="^\[*(WIP|wip)"
    actions:
      merge:
        method: merge
        strict: smart
        strict_method: rebase
