sudo: false

addons:
  apt:
    packages:
      - enchant
      - python-jsonschema
      - python-yaml

language: python

python:
  - 3.6

install:
  - pip install sphinx sphinx-rtd-theme sphinxcontrib-spelling

script:
  - make check
